# Generated by Django 5.2.7 on 2025-10-23 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encryptionhistory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Encryption Histories'},
        ),
        migrations.RenameField(
            model_name='encryptionhistory',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='encryptionhistory',
            old_name='operation',
            new_name='operation_type',
        ),
        migrations.RemoveField(
            model_name='encryptionhistory',
            name='algorithm',
        ),
        migrations.AddField(
            model_name='encryptionhistory',
            name='key_used',
            field=models.CharField(default='NOT_RECORDED', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='dark', max_length=20)),
                ('auto_clear', models.BooleanField(default=True)),
                ('secure_wipe', models.BooleanField(default=True)),
                ('audit_trail', models.BooleanField(default=False)),
                ('encryption_algorithm', models.CharField(default='aes-256', max_length=20)),
                ('key_derivation', models.CharField(default='pbkdf2', max_length=20)),
                ('font_size', models.CharField(default='medium', max_length=10)),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
